on: pull_request
name: PR Review
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  test-composer-files:
    name: Validate composer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
        dependency-version: [ prefer-lowest, prefer-stable ]
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          coverage: none
          tools: composer:v2
      # https://github.com/shivammathur/setup-php#cache-composer-dependencies
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Validate composer files
        run: |
          composer validate --strict composer.json
          # Check that dependencies resolve.
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

  php-check-coding-standards:
    name: PHP - Check Coding Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
        dependency-version: [ prefer-lowest, prefer-stable ]
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          coverage: none
          tools: composer:v2
      # https://github.com/shivammathur/setup-php#cache-composer-dependencies
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-progress
      - name: PHPCS
        run: |
          composer coding-standards-check/phpcs

  php-code-analysis:
    name: PHP code analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.1' ]
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json, gd
          coverage: none
          tools: composer:v2
      # https://github.com/shivammathur/setup-php#cache-composer-dependencies
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: drupal-check
        run: |
          # We need a Drupal project to run drupal-check (cf. https://github.com/mglaman/drupal-check#usage)
          # Install Drupal
          composer --no-interaction create-project drupal/recommended-project:^10 drupal
          # Copy our module source code into the Drupal module folder.
          mkdir -p drupal/web/modules/contrib/os2forms_user_field_lookup
          cp -r os2forms_user_field_lookup.* composer.json src drupal/web/modules/contrib/os2forms_user_field_lookup
          
          composer --working-dir=drupal --no-interaction config minimum-stability dev
          
          # Allow all plugins
          composer --working-dir=drupal config --no-plugins allow-plugins true
          
          # Add our module as a composer repository.
          composer --working-dir=drupal --no-interaction config --append repositories.itk-dev/os2forms_user_field_lookup path web/modules/contrib/os2forms_user_field_lookup
          # Restore Drupal composer repository.
          # composer --working-dir=drupal --no-interaction config --append repositories.drupal composer https://packages.drupal.org/8
          
          # Make Drupal 10 compatible
          composer --working-dir=drupal --no-interaction require psr/http-message:^1.0
          composer --working-dir=drupal --no-interaction require 'mglaman/composer-drupal-lenient'
          composer --working-dir=drupal config --no-plugins --merge --json extra.drupal-lenient.allowed-list '["drupal/coc_forms_auto_export", "drupal/webform_node_element"]'

          # Require our module.
          composer --working-dir=drupal --no-interaction require 'itk-dev/os2forms_user_field_lookup:*'
          
          # Check code
          composer --working-dir=drupal --no-interaction require --dev drupal/core-dev
          cd drupal/web/modules/contrib/os2forms_user_field_lookup
          # Remove our non-dev dependencies to prevent duplicated Drupal installation
          # PHP Fatal error:  Cannot redeclare drupal_get_filename() (previously declared in /home/runner/work/os2forms_user_field_lookup/os2forms_user_field_lookup/drupal/web/modules/contrib/os2forms_user_field_lookup/vendor/drupal/core/includes/bootstrap.inc:190) in /home/runner/work/os2forms_user_field_lookup/os2forms_user_field_lookup/drupal/web/core/includes/bootstrap.inc on line 190
          # Use sed to remove the "require" property in composer.json
          sed -i '/^\s*"require":/,/^\s*}/d' composer.json
          composer --no-interaction install
          composer code-analysis
